name: Update Electron Dependencies

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every 12 hours
    - cron:  '0 0/12 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  update-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false
      - run: yarn install
      - name: Build and update dependencies
        run: |
          set -x
          yarn update
          yarn build
          # Check if there are any changes to commit
          git status --porcelain
      - name: Publish from main if necessary
        if: github.ref == 'refs/heads/main'
        run: |
          set -x
          yarn run release
